### ISSUE TITLE
Sortable & Paginated table views

### ISSUE THREAD

**Issue by drinks** [sunlightlabs/datajam#26]
Sorting on the server side to deal with pagination properly, pagination could be a simple 'show more' / pjax call [#27]

**Comment by drinks** [comment]
Deployed the latest to stage. Looks good, but it's got me thinking a bit about workflow. Can we put the new template form up top, and hide it by default? There could then be a button, 'Create a new template', to the right of the page title to slide down the new template form. Finally, we'd enable infinite scrolling on the table views to load more rows rather than reloading on pagination. Sound good?

**Comment by elcuervo** [comment]
Ok, i understand, i'll make a new issue for the new form feature. This applies for all the new form isn't it?.
I understand about the infinite scrolling, i'll add it pretty soon.

**Comment by drinks** [comment]
Great. Still sorta thinking this through.. let's toggle new form vs. list view with nav pills, a la http://twitter.github.com/bootstrap/components.html#navs

Default will would say 'Event List', 'Event Template List', 'Embed Template List', etc.
Other one would say 'New Event', 'New Event Template', 'New Embed Template', etc.

**Comment by drinks** [comment]
Reopening this as there are a few issues with the way pagination buttons are drawn / rebound. I'm planning to merge in a branch that reverts to normal pjax pagination (vs the full replacement that's happening now), so I can implement infinite scrolling in a scalable way. In either case (current HEAD vs my branch), pagination buttons are being replaced on each pjax call, and not rebound, leading to a full page load every other action.

It needs to be possible to manage whatever pagination scheme we put in place unobtrusively and without losing event bindings. A refactor of this code should also not include js embedded directly in application.html.erb as well. Not 100% on what the final state of this needs to be, but willing to close this story and open a new one once filter boxes and pagination buttons are managed correctly.

**Comment by elcuervo** [comment]
This is solved with #31 isn't it?

**Comment by drinks** [comment]
Let me deploy and take a look, to be sure that it's not still happening on sort...

**Comment by drinks** [comment]
Entirely possible that the error from 53889c6 is causing this, but sorting seems to no longer being loaded via pjax.

**Comment by drinks** [comment]
Ok, with the error gone, this is still happening. Sorting should still use pjax, currently it reloads the page.
